import React, { useEffect, useState } from "react";
import { ethers } from "ethers";
import { PublicFooter, PublicHeader } from "./landing.jsx";

const API = (url, options = {}) => fetch(url, { credentials: "same-origin", ...options }).then(async response => {
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw Error(data.error || `Request failed (${response.status})`);
  return data;
});

function shortAddress(value) { return value ? `${value.slice(0, 6)}…${value.slice(-4)}` : ""; }

export default function AdminApp() {
  const [phase, setPhase] = useState("login"), [ticket, setTicket] = useState(null), [code, setCode] = useState(""), [message, setMessage] = useState(""), [user, setUser] = useState(null), [keys, setKeys] = useState([]), [env, setEnv] = useState({}), [qr, setQr] = useState(null);
  const [form, setForm] = useState({ provider: "", label: "production", secret: "", monthlyLimit: "" });
  const refresh = () => API("/api/admin/api-keys").then(data => { setKeys(data.keys || []); setEnv(data.envProviders || {}); }).catch(error => setMessage(error.message));
  useEffect(() => { if (phase === "panel") refresh(); }, [phase]);
  useEffect(() => { if (phase !== "enroll" || !ticket) return; API("/api/auth/totp-setup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ticket }) }).then(data => setQr(data.qrDataUrl)).catch(error => setMessage(error.message)); }, [phase, ticket]);
  const connect = async () => { try { if (!window.ethereum) throw Error("An EVM wallet extension is required."); const provider = new ethers.BrowserProvider(window.ethereum), signer = await provider.getSigner(), address = await signer.getAddress(); const nonce = await API("/api/auth/nonce", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ address }) }); const signature = await signer.signMessage(nonce.message); const verified = await API("/api/auth/verify-wallet", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ challengeId: nonce.challengeId, signature }) }); setTicket(verified.ticket); setPhase(verified.phase); setMessage(""); } catch (error) { setMessage(error.message); } };
  const verify = async () => { try { const data = await API("/api/auth/verify-totp", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ticket, code }) }); setUser(data); setPhase("panel"); setMessage(""); } catch (error) { setMessage(error.message); } };
  const addKey = async event => { event.preventDefault(); try { await API("/api/admin/api-keys", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, monthlyLimit: Number(form.monthlyLimit || 0) }) }); setForm({ provider: "", label: "production", secret: "", monthlyLimit: "" }); setMessage("Encrypted API key stored."); refresh(); } catch (error) { setMessage(error.message); } };
  if (phase !== "panel") return <><PublicHeader legal/><main className="auth-card"><div className="eyebrow">Protected workspace</div><h1>{phase === "enroll" ? "Set up authenticator" : phase === "totp" ? "Enter authenticator code" : "Admin access"}</h1>{phase === "login" ? <button className="button" onClick={connect}>Connect admin wallet</button> : <>{phase === "enroll" && (qr ? <img className="admin-qr" src={qr} alt="Authenticator setup QR code" /> : <p className="muted">Preparing authenticator setup…</p>)}<p className="muted">{phase === "enroll" ? "Scan the code, then enter the current six-digit authenticator code." : "Enter the current six-digit authenticator code to continue."}</p><input className="amount-input" inputMode="numeric" maxLength="6" value={code} onChange={event => setCode(event.target.value.replace(/\D/g, "").slice(0, 6))} placeholder="000000"/><button className="button" onClick={verify}>Verify</button></>}<p className="error" role="alert">{message}</p></main><PublicFooter/></>;
  return <><PublicHeader legal/><main className="admin-main"><div className="admin-heading"><div><div className="eyebrow">Infrastructure</div><h1>API Infrastructure Monitor</h1><p className="muted">{shortAddress(user?.address)} · {user?.role}</p></div><button className="button secondary" onClick={refresh}>Refresh</button></div><section className="admin-stats"><div><b>{keys.length + Object.values(env).filter(Boolean).length}</b><span>configured providers</span></div><div><b>{keys.reduce((sum, key) => sum + key.requestCount, 0)}</b><span>tracked requests</span></div><div><b>{keys.filter(key => key.active).length}</b><span>active vault keys</span></div></section><section className="admin-panel"><h2>Vault keys</h2>{keys.map(key => <div className="key-row" key={key.id}><div><b>{key.provider}</b><span>{key.label} · {key.masked}</span></div><div><span>{key.requestCount} requests{key.monthlyLimit ? ` · ${Math.min(100, Math.round(key.requestCount / key.monthlyLimit * 100))}%` : ""}</span><span>{key.active ? "active" : "paused"}</span></div></div>)}{!keys.length && <p className="muted">No encrypted vault keys yet.</p>}</section>{user?.role === "owner" && <section className="admin-panel"><h2>Add API key</h2><form onSubmit={addKey} className="key-form"><input placeholder="Provider" value={form.provider} onChange={event => setForm({ ...form, provider: event.target.value })}/><input placeholder="Label" value={form.label} onChange={event => setForm({ ...form, label: event.target.value })}/><input type="password" placeholder="Secret" value={form.secret} onChange={event => setForm({ ...form, secret: event.target.value })}/><input type="number" min="0" placeholder="Monthly limit" value={form.monthlyLimit} onChange={event => setForm({ ...form, monthlyLimit: event.target.value })}/><button className="button" type="submit">Store encrypted key</button></form></section>}<p className="error" role="alert">{message}</p></main><PublicFooter/></>;
}
